### ISSUE TITLE
Microsub Channels

### ISSUE THREAD

**Issue by stephenpieper** [swentel/indigenous-desktop#45]
I've managed to get the app (Mac version) connected to Wordpress for posting but I can't get my microsub channels to load. I've added a token from Wordpress and my Aperture endpoint into settings. Is there a step I'm missing?

**Comment by swentel** [comment]
> Is there a step I'm missing?

I don't think so. The likeliness of this being a bug in the app is much bigger at this stage of development :)

Could you try the following:

- In the app: Go to 'Settings' and toggle 'Debug messages'
- Go the menu bar (not in app, but in the bar above), click 'View' -> 'Toggle developer tools'
- Go back to channels in the app, and then go to menu bar, click 'View' -> 'Force reload' 

Hopefully, you see something on the right in the developer tools. Either good or bad, something would be a good start.

My assumption is that there might be something wrong while parsing the content, so some JS error will be triggered.

**Comment by stephenpieper** [comment]
Thanks. This is the error appearing in the developers tools. 
"Failed to load resource: the server responded with a status of 403 ()"

I can post notes and images to Wordpress from the Post page. It's just the microsub part that's not working,

**Comment by swentel** [comment]
Ok, so access denied. That means the token isn't valid for some reason. Trying to think what might be wrong here. My own setup uses micropub and microsub on the same server (my own site), so that's one difference. But that shouldn't matter too much - at least I think so.

**Comment by swentel** [comment]
This might be a weird question: do you use the android client by any chance as well? If that works, I might have a clue - or at least some more places where I can look to start debugging :)

**Comment by swentel** [comment]
I do have one clue though: Did you generate a new token for this to test? In that case, the scopes might not be set right.

**Comment by stephenpieper** [comment]
I don't use the android client (iOS).

I've tried a few tokens with different scopes but still no luck. I'm sure I've covered them all but could you tell me exactly which ones I should be using?

**Comment by swentel** [comment]
For getting the channels and timeline 'read' should be enough.

**Comment by swentel** [comment]
Just wondering, how do you create new tokens. Installed wordpress locally, but can't a place where to create tokens manually, that would probably allow me to help debugging.

**Comment by swentel** [comment]
nevermind, just found it! :)

**Comment by swentel** [comment]
I think I found the problem: Aperture compares the 'me' value that is send along with the response when asking for the token. The problem with generated tokens is that the me value is set to something like 'http(s)://domain/author/authorname', and what is stored in aperture is just http(s)://domain/ - and then Aperture returns a 403.

**Comment by swentel** [comment]
I checked with Aaron and the url which is stored is 'https://stephenpieper.net/', so the 'me' value for the token should also be that.

Apparently, you can set the 'root' user for the 'me' value via settings. Note that you also need the 'Website' filled in 'Your profile'. Then, everything should be fine :)

<GWG> It only does that if you don't configure it in settings
<GWG> You have to declare what user reflects the root

**Comment by swentel** [comment]
Added this information in the README.
